### ISSUE TITLE
pls fix this

### ISSUE THREAD

**Issue by mcrzy** [Auties00/Reboot-Launcher#100]
every time i try to start the server it just shows this
![image_2024-09-14_122248316](https://github.com/user-attachments/assets/79e2460c-c785-4422-9aac-2366e53c9f2d)

**Comment by Auties00** [comment]
Not a launcher bug, but I’ll leave it open. 
if you are using season 20 or greater you need to compile the reboot game server yourself and follow the instructions in that gui 
I’ll ask milxnor if he can do something about it

**Comment by mcrzy** [comment]
how do i compile it?

**Comment by Auties00** [comment]
Fixed in 10.0.0, compilation is no longer necessary
