### ISSUE TITLE
it doesnt launch and says it says cannot ping embedded backend

### ISSUE THREAD

**Issue by JBHIFI1** [Auties00/Reboot-Launcher#104]
it doesnt launch and says it says cannot ping embedded backend

**Comment by Auties00** [comment]
Send the launcher.log file
Open the settings tab, click installation directory and you’ll find the file there 
Make sure you start the backend before sending me the file or it won’t contain the requested info

**Comment by JBHIFI1** [comment]
can i just share screen

**Comment by JBHIFI1** [comment]
on ds

**Comment by Auties00** [comment]
No I need the file

**Comment by JBHIFI1** [comment]
where is it

**Comment by Auties00** [comment]
> Send the launcher.log file Open the settings tab, click installation directory and you’ll find the file there Make sure you start the backend before sending me the file or it won’t contain the requested info

Here

**Comment by JBHIFI1** [comment]
oh

**Comment by JBHIFI1** [comment]
[launcher.log](https://github.com/user-attachments/files/17155271/launcher.log)

**Comment by JBHIFI1** [comment]
i cant start backend it says cant ping it

**Comment by JBHIFI1** [comment]
REPLY PLEASSSE

**Comment by Auties00** [comment]
> [launcher.log](https://github.com/user-attachments/files/17155271/launcher.log)

It looks like it’s starting correctly, mind sending a video? Also are you on the latest release?
