### ISSUE TITLE
Cannot log in into fortnite: authentication error (cobalt,memory,console,reboot) Part 2

### ISSUE THREAD

**Issue by LucaRoblox** [Auties00/Reboot-Launcher#112]
Can maybe someone help me, i wanna play 10.40 but i can't cuz for the authentication errors, i tried fixing this issue but the owner wasn't responding for almost 2 days but now, keeps crashing only the game server manager, here is the error:
![Screenshot 2024-10-13 095709](https://github.com/user-attachments/assets/d7fc9113-7ac6-4c3d-a723-5f558a703276)
And 20% of the time gives this error:
![Screenshot 2024-10-10 214026](https://github.com/user-attachments/assets/48acd203-53ae-4772-a61a-719751f39266)
I hope someone helps me...

**Comment by skillshit** [comment]
Im getting the same error now did u fix it?

**Comment by LucaRoblox** [comment]
nope and imma close this cuz i guess it's impossible to resolve

**Comment by Auties00** [comment]
Ill send an exe to test later

**Comment by LucaRoblox** [comment]
ok

**Comment by LucaRoblox** [comment]
still waiting for it

**Comment by LucaRoblox** [comment]
@Auties00 i actually found that the backend before the game client starts, crashes. And with this makes the game crash

**Comment by LucaRoblox** [comment]
![image](https://github.com/user-attachments/assets/98c41831-6a1b-41e4-a1e3-d098baa9ef38)
@Auties00

**Comment by LucaRoblox** [comment]
this is done while launching 10.40.0, the version which i have problems

**Comment by LucaRoblox** [comment]
@Auties00 i installed an older version of reboot and... IT WORKED! guess imma gonna use this until idk. Thanks for helping btw. I appreciated your help :)

**Comment by LucaRoblox** [comment]
guess imma leave it open in case maybe owner replies with the exe thing

**Comment by hiyyihkep1er** [comment]
which version of reboot did you use im having the same issue

**Comment by LucaRoblox** [comment]
> which version of reboot did you use im having the same issue

10.40

**Comment by Auties00** [comment]
Fixed  completely in latest version, if it happens now it means that the build is unsupported
