### ISSUE TITLE
Cobalt.dll is either not designed to run on Windows or it contains an error. 

### ISSUE THREAD

**Issue by Dog0719** [Auties00/Reboot-Launcher#119]
Cobalt.dll gets deleted quietly by my pc, when I reinstall the lost dll and run Reboot, it throws this error up. 

![image](https://github.com/user-attachments/assets/31b7eab5-c412-4e72-8cb4-2967d5e24df3)

**Comment by Auties00** [comment]
Probably for corrupted by your anti virus
