### ISSUE TITLE
Milxnor's LawinServer V2 not detected by the launcher

### ISSUE THREAD

**Issue by ChrisGamez10** [Auties00/Reboot-Launcher#128]
I have LawinServer running so I can play locally and it appears each time I go to launch a Fortnite client, I get this popup saying basically there is no server running. 
![image](https://github.com/user-attachments/assets/023c1e56-be46-4d6b-9070-2d2c674fa161)
I'm not sure where to go from here as I am absolutely sure it is running, so some help would be appreciated.

**Comment by Auties00** [comment]
The backend and game server are two different things 
Take the tour in the launcher
