### ISSUE TITLE
need help on reboot launcher

### ISSUE THREAD

**Issue by RazfoxKC** [Auties00/Reboot-Launcher#133]
plz help me idk how to do for it work[](url)
![image_2024-11-15_153418117](https://github.com/user-attachments/assets/0c4886a8-58ff-48b1-924d-347581070641)

**Comment by emu646** [comment]
I have the same problem.
PLease someone help

**Comment by emu646** [comment]
OMG! I FOUNDED!
Go to the reboot discord server, go to support and there someone sent the reboot file thath you need.
After you've douwnloaded the file, put it in dlls
