### ISSUE TITLE
reboot dlls 

### ISSUE THREAD

**Issue by phantomsxb** [Auties00/Reboot-Launcher#135]
it keeps saying failed to download reboot dlls and nothing happens when i click retry

**Comment by steeve776** [comment]
when i try to launch it says error status code 404

**Comment by Auties00** [comment]
This will be fixed in the next version, download it from the discord in the meanwhile

**Comment by Horizon5477** [comment]
Is there a version that works currently?

**Comment by Auties00** [comment]
Fixed in 10.0.0
