### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by Huiledol1** [Auties00/Reboot-Launcher#136]
backbend and ver works correctly, my game just crashes

**Comment by DaComputer22** [comment]
Let me start off by saying, I don't know how to solve your problem, but it sounds like you are able to launch the game. I have the same problem as issue #133 , and I think I just need the reboot.dll (in *\Reboot Launcher\dlls) for mine to start working. If you have this file, could you send it to me? I'll probably just get the same crashes as you are getting, but I want to try anyway.
