### ISSUE TITLE
Future already completed

### ISSUE THREAD

**Issue by ololololoedad** [Auties00/Reboot-Launcher#139]
when i install the thing and then run backend and then launch fortnite i get the error code of a file that doesnt exist??Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43)
#1      DllController.downloadCriticalDllInteractive.<anonymous closure> (package:reboot_launcher/src/controller/dll_controller.dart:230)
<asynchronous suspension>

**Comment by Auties00** [comment]
Fixed in 10.0.0
