### ISSUE TITLE
my host crash instantly

### ISSUE THREAD

**Issue by chelovek228** [Auties00/Reboot-Launcher#145]
I did the tutorial and I constantly get this error, I dug a lot into the source and it was to no avail, I even reinstalled another version of fortnite, but nothing changed
![image](https://github.com/user-attachments/assets/e7c1562a-442a-4e58-968f-abece9949f9f)

https://github.com/user-attachments/assets/232f2369-9f0b-4de3-a6ff-aa2d99b32eb5

Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000028

0x00007ff62ce79c56 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62ce79ac7 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62ce7908d FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62ce6697a FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62ce68404 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff6298e1df2 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62ce78fd1 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62ce5b152 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62d07dadb FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62acd120f FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62ad00bb2 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62ad0166f FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62d0834d0 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62d3f5e24 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62d797f90 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62d3fc5a6 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62d7b6af2 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62d3208da FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62d7307a5 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62d3057e5 FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62d30a5ec FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62afa933c FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff6297e910c FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff6297ef9cc FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff6297efa3a FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff6297f986b FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ff62e8f8e4e FortniteClient-Win64-Shipping.exe!UnknownFunction []
0x00007ffe2d8c7344 KERNEL32.DLL!UnknownFunction []
0x00007ffe2e0426b1 ntdll.dll!UnknownFunction []

**Comment by Auties00** [comment]
> I did the tutorial and I constantly get this error, I dug a lot into the source and it was to no avail, I even reinstalled another version of fortnite, but nothing changed ![image](https://private-user-images.githubusercontent.com/78218298/389273694-e7c1562a-442a-4e58-968f-abece9949f9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NTQwNzUsIm5iZiI6MTczMjQ1Mzc3NSwicGF0aCI6Ii83ODIxODI5OC8zODkyNzM2OTQtZTdjMTU2MmEtNDQyYS00ZTU4LTk2OGYtYWJlY2U5OTQ5ZjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDEzMDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYzk4NGY2ZjZhYjg0YTZjOTRlNjY3NTBhNWE5Y2FlYWNjZTNlZjQ1ZGNjNjgyNGNiYWJhMGNiNzJmNjkwM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HNaqDXLBpam4som6bh1qbU7tHI8jDzDr5H4lN-1WFnQ)
> 
>  fortnite-20241124-14142102_1kkL4pZF.mp4 
> 
> Fatal error!
> 
> Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000028
> 
> 0x00007ff62ce79c56 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62ce79ac7 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62ce7908d FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62ce6697a FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62ce68404 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff6298e1df2 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62ce78fd1 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62ce5b152 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62d07dadb FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62acd120f FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62ad00bb2 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62ad0166f FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62d0834d0 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62d3f5e24 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62d797f90 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62d3fc5a6 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62d7b6af2 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62d3208da FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62d7307a5 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62d3057e5 FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62d30a5ec FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62afa933c FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff6297e910c FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff6297ef9cc FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff6297efa3a FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff6297f986b FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ff62e8f8e4e FortniteClient-Win64-Shipping.exe!UnknownFunction [] 0x00007ffe2d8c7344 KERNEL32.DLL!UnknownFunction [] 0x00007ffe2e0426b1 ntdll.dll!UnknownFunction []

This means that the version you are using isn't supported
