### ISSUE TITLE
supabase too many connected users

### ISSUE THREAD

**Issue by VEXXX945** [Auties00/Reboot-Launcher#146]
Exception: "Too many connected users"
#0      SupabaseStreamBuilder._addException (package:supabase/src/supabase_stream_builder.dart:293)
#1      SupabaseStreamBuilder._getStreamData.<anonymous closure> (package:supabase/src/supabase_stream_builder.dart:199)
#2      RealtimeChannel.subscribe.<anonymous closure> (package:realtime_client/src/realtime_channel.dart:201)
#3      Push._matchReceive.<anonymous closure> (package:realtime_client/src/push.dart:133)
#4      Iterable.forEach (dart:core/iterable.dart:347)
#5      Push._matchReceive (package:realtime_client/src/push.dart:132)
#6      Push.startTimeout.<anonymous closure> (package:realtime_client/src/push.dart:96)
#7      RealtimeChannel.trigger (package:realtime_client/src/realtime_channel.dart:693)
#8      new RealtimeChannel.<anonymous closure> (package:realtime_client/src/realtime_channel.dart:89)
#9      RealtimeChannel.trigger (package:realtime_client/src/realtime_channel.dart:693)
#10     RealtimeClient.onConnMessage.<anonymous closure>.<anonymous closure> (package:realtime_client/src/realtime_client.dart:317)
#11     Iterable.forEach (dart:core/iterable.dart:347)
#12     RealtimeClient.onConnMessage.<anonymous closure> (package:realtime_client/src/realtime_client.dart:317)
#13     new RealtimeClient.<anonymous closure> (package:realtime_client/src/realtime_client.dart:133)
#14     RealtimeClient.onConnMessage (package:realtime_client/src/realtime_client.dart:300)
#15     RealtimeClient.connect.<anonymous closure> (package:realtime_client/src/realtime_client.dart:163)
#16     _rootRunUnary (dart:async/zone.dart:1407)
#17     _CustomZone.runUnary (dart:async/zone.dart:1308)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#21     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123)
#22     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253)
#23     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153)
#24     _rootRunUnary (dart:async/zone.dart:1407)
#25     _CustomZone.runUnary (dart:async/zone.dart:1308)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#29     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#30     _StreamController._add (dart:async/stream_controller.dart:658)
#31     _rootRunUnary (dart:async/zone.dart:1407)
#32     _CustomZone.runUnary (dart:async/zone.dart:1308)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#37     _StreamController._add (dart:async/stream_controller.dart:658)
#38     _StreamController.add (dart:async/stream_controller.dart:606)
#39     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144)
#40     _rootRunUnary (dart:async/zone.dart:1407)
#41     _CustomZone.runUnary (dart:async/zone.dart:1308)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63)
#46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13)
#47     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332)
#48     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226)
#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111)
#50     _rootRunUnary (dart:async/zone.dart:1407)
#51     _CustomZone.runUnary (dart:async/zone.dart:1308)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#56     _StreamController._add (dart:async/stream_controller.dart:658)
#57     _StreamController.add (dart:async/stream_controller.dart:606)
#58     _Socket._onData (dart:io-patch/socket_patch.dart:2449)
#59     _rootRunUnary (dart:async/zone.dart:1407)
#60     _CustomZone.runUnary (dart:async/zone.dart:1308)
#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#64     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#65     _StreamController._add (dart:async/stream_controller.dart:658)
#66     _StreamController.add (dart:async/stream_controller.dart:606)
#67     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1116)
#68     _rootRun (dart:async/zone.dart:1391)
#69     _CustomZone.run (dart:async/zone.dart:1301)
#70     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#71     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#72     _rootRun (dart:async/zone.dart:1399)
#73     _CustomZone.run (dart:async/zone.dart:1301)
#74     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233)
#75     TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:435)
#76     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#77     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#78     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

**Comment by Auties00** [comment]
Fixed in 10.0.0
