### ISSUE TITLE
fix a bug project reboot

### ISSUE THREAD

**Issue by kokaobar** [Auties00/Reboot-Launcher#152]
![Desktop Screenshot 2024 11 27 - 15 35 17 33](https://github.com/user-attachments/assets/5c674d13-6e64-4175-8fa4-39f0d41d79d2)
 
pls help

**Comment by Auties00** [comment]
> ![Desktop Screenshot 2024 11 27 - 15 35 17 33](https://private-user-images.githubusercontent.com/189869391/390429041-5c674d13-6e64-4175-8fa4-39f0d41d79d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTUwNDcsIm5iZiI6MTczMjcxNDc0NywicGF0aCI6Ii8xODk4NjkzOTEvMzkwNDI5MDQxLTVjNjc0ZDEzLTZlNjQtNDE3NS04ZmE0LTM5ZjBkNDFkNzlkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QxMzM5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmFlMjQ5ZTVjMDc3ZjhlYzEzYTYyOTBjNmQxODBhOGE5Y2I1YjdkYWIxYTc1YTRjZjQ0ZWFjZjhhNjhiMzdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3U31KU-sh99F-nKfQXFXWWEqnoDJrFQuXoPtRcM49X4)
> 
> pls help

https://github.com/Auties00/Reboot-Launcher/issues/135
