### ISSUE TITLE
WMIC Powershell error when i try to add a version

### ISSUE THREAD

**Issue by gamerjag12** [Auties00/Reboot-Launcher#156]
i preferred using reboot launcher version launcher 8.1.08.1.0 but it dissappeared with the discord server, so i tried the new one and cant even add a version i get this error when i do so. WMIC has been reinstalled and nothing changed

NotFoundException{message: Could not locate wmic binary at C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe}
#0      DiskSpace.scan (package:universal_disk_space/src/disk_space.dart:115)
<asynchronous suspension>
#1      _AddVersionDialogState.initState.<anonymous closure> (package:reboot_launcher/src/messenger/implementation/version.dart:50)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:524)
<asynchronous suspension>
#3      _AddVersionDialogState.build.<anonymous closure>.<anonymous closure> (package:reboot_launcher/src/messenger/implementation/version.dart:74)
<asynchronous suspension>
#4      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:638)
<asynchronous suspension>

![Screenshot 2024-11-28 164603](https://github.com/user-attachments/assets/15f590a7-e9b0-46c8-819c-67fc12999a46)

**Comment by Auties00** [comment]
Im pretty sure this is a problem of your installation, I’ve never seen anyone with that issue. Which version of windows are you on?

**Comment by gamerjag12** [comment]
i figured it out, the program specifies system files exclusively under the C:\ drive. but my system drive is mounted as F:\ so i just copied the nessecary system files and their folder tree to my external drive which is mounted as C:\ and now it works!

**Comment by Auties00** [comment]
Fixed in 10.0.3
