### ISSUE TITLE
I cant add a build 

### ISSUE THREAD

**Issue by BadiieYT** [Auties00/Reboot-Launcher#160]
It gives me this error message 

NotFoundException{message: Could not locate wmic binary at C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe}
#0      DiskSpace.scan (package:universal_disk_space/src/disk_space.dart:115)
<asynchronous suspension>
#1      _AddVersionDialogState.initState.<anonymous closure> (package:reboot_launcher/src/messenger/implementation/version.dart:54)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:524)
<asynchronous suspension>
#3      _AddVersionDialogState.build.<anonymous closure>.<anonymous closure> (package:reboot_launcher/src/messenger/implementation/version.dart:78)
<asynchronous suspension>
#4      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:638)
<asynchronous suspension>

**Comment by Auties00** [comment]
> It gives me this error message
> 
> NotFoundException{message: Could not locate wmic binary at C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe} #0 DiskSpace.scan (package:universal_disk_space/src/disk_space.dart:115) #1 _AddVersionDialogState.initState. (package:reboot_launcher/src/messenger/implementation/version.dart:54) #2 Future.wait. (dart:async/future.dart:524) #3 _AddVersionDialogState.build.. (package:reboot_launcher/src/messenger/implementation/version.dart:78) #4 _FutureBuilderState._subscribe. (package:flutter/src/widgets/async.dart:638)

This looks like a corrupted windows install, you are missing a critical exe
