### ISSUE TITLE
Need help starting game in old versions of Fortnite

### ISSUE THREAD

**Issue by Videogamer555** [Auties00/Reboot-Launcher#170]
I can run old versions including 1.8.2 (the 3rd version of Season-1) but the Start button to actually go into a match does nothing. Also manually typing "open 127.0.0.1" does nothing. I can use an old trick to load the terrain by first typing "open athena_terrain" and then "toggledebugcamera" and then fly around with the camera. But that does absolutely nothing to spawn a player character. Please add support for old versions including Season-0 and Season-1.

**Comment by Auties00** [comment]
Already supported, go on discord for tech support
