### ISSUE TITLE
Problem with editing while on build mode Season 9 and above.

### ISSUE THREAD

**Issue by EliasFN** [Auties00/Reboot-Launcher#174]
When ever I pick up something and then edit while on build mode, it pull it out after confirming an edit this only happening on Season 9 and above (rest of the seasons except 0,1,2,3,4,5,6,7,8)
https://github.com/user-attachments/assets/b329184e-3037-4781-bcd0-f0caf98c3fec

**Comment by Auties00** [comment]
This is a game server bug, report it on the reboot project repo
