### ISSUE TITLE
console commands not working in 12.41

### ISSUE THREAD

**Issue by HotCatpolska** [Auties00/Reboot-Launcher#176]
does somebody know why i cant start the event in reboot im on 12.41 travis scoot event but i type in "cheat startevent" and it doesnt work and no other command works exept "open 127.0.0.1" why?

**Comment by DreamyBranch** [comment]
commands other than (open 127.0.0.1) dont work at all for me

**Comment by DreamyBranch** [comment]
Can you trying going down a different version?

**Comment by Auties00** [comment]
Commands are disabled by default, you need to enable cheats
