### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Dog0719** [Auties00/Reboot-Launcher#180]
HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:143)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:920)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1049)
<asynchronous suspension>

**Comment by Auties00** [comment]
Update your launcher 
Disable any VPN/Proxy/Packet sniffer(wireshark/fiddlwr/…)

**Comment by Dog0719** [comment]
I'm on the current version of the launcher, don't have a vpn, proxy or anything else

**Comment by Auties00** [comment]
Is your date and time correct?

**Comment by Dog0719** [comment]
Yes

**Comment by Auties00** [comment]
Well then either someone is pulling a man in the middle attack on your machine or something very strange is wrong

**Comment by Dog0719** [comment]
Antivirus ain't picking up on anything, strange.

Is there a way for me to add versions manually via the launcher's files? There's a "game storage" file and I'm curious if I can just add it to there, but I don't know the format

**Comment by Auties00** [comment]
Click on the version selector 
Add new version 
Select as source this Pc

**Comment by Dog0719** [comment]
I can't, that's what's giving me this error lol

**Comment by Auties00** [comment]
I see I’ll add a check in the next version to add local builds if the remote build downloader can’t start
