### ISSUE TITLE
crashes as soon as i try spawn a bot

### ISSUE THREAD

**Issue by zen-crixy-dev** [Auties00/Reboot-Launcher#183]
i type cheat spawnbot and then it just closes the game

LoginId:dad8441342e98326478546a60c9709f7
EpicAccountId:d994239042cf445a9ca5e7dad78d5721

Unhandled exception

FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
FortniteClient_Win64_Shipping
kernel32
ntdll

**Comment by Auties00** [comment]
This is a game server issue
