### ISSUE TITLE
Reboot Launcher

### ISSUE THREAD

**Issue by Avene11** [Auties00/Reboot-Launcher#196]
Hello Dear Supporter,
I have noticed when I am trying to get in a round in the version 19.10 I am just getting sent back to the Lobby and worse when I starting a Host, my console is closing after about 15seconds and I don't know what to do and I wanted to ask you if it is a bug or is it because of me. I have seen the tweet in the info on you're Discord Server and it says Season 19 might not work perfectly **but** is avaible for testing and I don't know if testing means getting in the game and be in the Lobby or if it means you can play.
Best Regards Avene11

**Comment by Auties00** [comment]
This is normal 
Version 19.10 is not supported as stated in the readme 
Go on discord for tech support
