### ISSUE TITLE
"Failed to open descriptor file"

### ISSUE THREAD

**Issue by Tropiksfaq** [Auties00/Reboot-Launcher#47]
When I press "Launch Fortnite" in the reboot launcher, I am met with a pop-up that says "Pinging embedded server" and then that tab closes, then i get a popup that says "Failed to open descriptor file../../../FortniteGame/FortniteGame.unproject" and it opens 2 of these, Im not sure what to do and yes I have run reboot launcher as administartor.
![Screenshot 2024-03-04 160450](https://github.com/Auties00/reboot_launcher/assets/162156955/dcb1fff0-ff62-4e5a-a791-dfc29d610eda)

**Comment by SwearvinLol** [comment]
Your build is corrupted. You have to reinstall the fortnite version.

**Comment by Auties00** [comment]
Gonna follow up on this issue

**Comment by ByZNexus** [comment]
Your build is corrupted
