### ISSUE TITLE
Add Windows 7 support

### ISSUE THREAD

**Issue by jonnyprogamer** [Auties00/Reboot-Launcher#58]
Hello, as the title says im unable to open the launcher because of this error, i downloaded from source and im able to run Lawin backend without any problem, the GUI app however does not start.
If it's possible to fix this or link some place where i can download older versions of the launcher it would be perfect
Thanks!

**Comment by jonnyprogamer** [comment]
I want to add that version 9.0.79.0.7 seems to work without any problem

**Comment by LouisGaming2941** [comment]
agree please add

**Comment by jonnyprogamer** [comment]
> agree please add

Don't worry dev is working on it, first he needs to polish some stuff, the issue is because the new Flutter version doesn't "support" Windows 7 and 8, however it still works perfectly on Win 8.
If you wish to use Reboot on Win 7 for now you have to use older version "9.0.79.0.7", and also because of some bugs only playing works on Win 7 even if you use that version, as if you try to host the DLL injection will make your game crash instantly for some reason.

**Comment by jonnyprogamer** [comment]
Could be possible to make it run using Win 7 extended kernel "VxKex" -> https://github.com/vxiiduu/VxKex 
Only problem would be UI renderer, apparently Flutter team switched to Direct Composition which only works on Win 8 and up.

**Comment by Auties00** [comment]
> Could be possible to make it run using Win 7 extended kernel "VxKex" -> https://github.com/vxiiduu/VxKex Only problem would be UI renderer, apparently Flutter team switched to Direct Composition which only works on Win 8 and up.

I could just rollback the flutter version, it’s not like I need any new features or anything. Obviously it’s not a very good solution for maintainability

**Comment by jonnyprogamer** [comment]
> I could just rollback the flutter version, it’s not like I need any new features or anything. Obviously it’s not a very good solution for maintainability
Yea that's probably the best solution, from the look of it their new "updates" did nothing much other than remove legacy stuff

**Comment by Auties00** [comment]
Added in 10.0.5 
Let me know if you have any other feature requests!
