### ISSUE TITLE
Failed to log in Fortnite : Authentification error (injected dll : Cobalt)

### ISSUE THREAD

**Issue by ByZNexus** [Auties00/Reboot-Launcher#78]
Basically i open 1.7.2 and once it fully loaded and right before the login process, it crashes and give me this error in reboot

Then i tried a new cobalt dll, but i couldn't inject the gameserver, as it would crash.

I then tried to launch the reboot's cobalt without launcher a gameserver, i did go past the login screen and on the lobby, but then once i injected the game server, it either crashed as soon as the number hit 0 to load the map or a few seconds after reboot became joinable.

But the error message on reboot is not only cobalt, but also memory and console.

I tried with other gameserver dlls that are like reboot, they seem to all have the same issue.

I tried with the embedded and local backend. Same thing.

My guess would be that the cobalt dll broke, but its easy to say than to fix.

Btw, reboot work on my other pc, which is odd

Thanks for reading

**Comment by Auties00** [comment]
Yeah this would be an interesting issue to fix

**Comment by ByZNexus** [comment]
> Yeah this would be an interesting issue to fix

I found a way to fix this

I looked thru the reboot server (in which im banned and idk why, @wallonia )

And i found this

Type "D:\ByZN\fortnite og\1.6.3\1.6.3\FortniteGame\Binaries\Win64\FortniteClient-Win64-Shipping.exe" -epicapp=Fortnite -epicenv=Prod -epiclocale=en-us -epicportal -skippatchcheck -nobe -fromfl=eac -fltoken=3db3ba5dcbd2e16703f3978d -caldera=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoiYmU5ZGE1YzJmYmVhNDQwN2IyZjQwZWJhYWQ4NTlhZDQiLCJnZW5lcmF0ZWQiOjE2Mzg3MTcyNzgsImNhbGRlcmFHdWlkIjoiMzgxMGI4NjMtMmE2NS00NDU3LTliNTgtNGRhYjNiNDgyYTg2IiwiYWNQcm92aWRlciI6IkVhc3lBbnRpQ2hlYXQiLCJub3RlcyI6IiIsImZhbGxiYWNrIjpmYWxzZX0.VAWQB67RTxhiWOxx7DBjnzDnXyyEnX7OljJm-j2d88G_WgwQ9wrE6lwMEHZHjBd1ISJdUO1UVUqkfLdU5nofBQ -AUTH_LOGIN=test -AUTH_PASSWORD=Eas223971 -AUTH_TYPE=epic

I put this in my cmd prompt and it opened reboot successfully, i then injected the reboot dll, and it didnt crashed, only in very rare occasions. I then launched a other instance on my configured era launcher with my backend, and it worked, i could go in game !

I thank you because you're the one who suggested this issue

**Comment by Auties00** [comment]
> > Yeah this would be an interesting issue to fix
> 
> I found a way to fix this
> 
> I looked thru the reboot server (in which im banned and idk why, @wallonia )
> 
> And i found this
> 
> Type "D:\ByZN\fortnite og\1.6.3\1.6.3\FortniteGame\Binaries\Win64\FortniteClient-Win64-Shipping.exe" -epicapp=Fortnite -epicenv=Prod -epiclocale=en-us -epicportal -skippatchcheck -nobe -fromfl=eac -fltoken=3db3ba5dcbd2e16703f3978d -caldera=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoiYmU5ZGE1YzJmYmVhNDQwN2IyZjQwZWJhYWQ4NTlhZDQiLCJnZW5lcmF0ZWQiOjE2Mzg3MTcyNzgsImNhbGRlcmFHdWlkIjoiMzgxMGI4NjMtMmE2NS00NDU3LTliNTgtNGRhYjNiNDgyYTg2IiwiYWNQcm92aWRlciI6IkVhc3lBbnRpQ2hlYXQiLCJub3RlcyI6IiIsImZhbGxiYWNrIjpmYWxzZX0.VAWQB67RTxhiWOxx7DBjnzDnXyyEnX7OljJm-j2d88G_WgwQ9wrE6lwMEHZHjBd1ISJdUO1UVUqkfLdU5nofBQ -AUTH_LOGIN=test -AUTH_PASSWORD=Eas223971 -AUTH_TYPE=epic
> 
> I put this in my cmd prompt and it opened reboot successfully, i then injected the reboot dll, and it didnt crashed, only in very rare occasions. I then launched a other instance on my configured era launcher with my backend, and it worked, i could go in game !
> 
> I thank you because you're the one who suggested this issue

Good to know, if you are available we can run some tests together to hopefully fix these Auth errors. If I had to guess it has to do with the timing for dlls injection. I also need to add an error handler for ue crashes and descriptors not going so people know it’s not the launcher’s fault. For

**Comment by ByZNexus** [comment]
> Good to know, if you are available we can run some tests together to hopefully fix these Auth errors. If I had to guess it has to do with the timing for dlls injection. I also need to add an error handler for ue crashes and descriptors not going so people know it’s not the launcher’s fault. For

Sure! Currently on my other pc which i think dont have any issues on reboot, ill get back on my other one on the 19th, but if you still want to run some tests on my current pc, im always free!

@wallonia is my discord username 😉
