### ISSUE TITLE
Corrupted Fortnite installation + White Compass

### ISSUE THREAD

**Issue by Justin240607** [Auties00/Reboot-Launcher#83]
Hello,

after launching Fortnite (5.40) with the newest version of the Reboot Launcher I get the following error message: Corrupted Fortnite installation. 
The game doesn´t start. I will attache the log file to the post. I already posted the same thing in the Discord and [had a discussion with Puppe. He has the same issue on that version.](https://discord.com/channels/998020695223193670/1274042103139405938)

I tried it on two separate computers with in total 3 different windows installations and various downloads of the 5.40 version. Furthermore the same files work in the Butterfly Launcher and a really old version (out of 2023) of the Reboot Launcher.

Another unrelated problem I have is that the compass in-game on the top of the screen is white. If I remember correctly it can be fixed by some .pak file or a setting in-game.

It would be great if someone could help me or fix the issues.

Thank you, 
Justin

[launcher.log](https://github.com/user-attachments/files/16639927/launcher.log)

**Comment by Auties00** [comment]
> Hello,
> 
> after launching Fortnite (5.40) with the newest version of the Reboot Launcher I get the following error message: Corrupted Fortnite installation. The game doesn´t start. I will attache the log file to the post. I already posted the same thing in the Discord and [had a discussion with Puppe. He has the same issue on that version.](https://discord.com/channels/998020695223193670/1274042103139405938)
> 
> I tried it on two separate computers with in total 3 different windows installations and various downloads of the 5.40 version. Furthermore the same files work in the Butterfly Launcher and a really old version (out of 2023) of the Reboot Launcher.
> 
> Another unrelated problem I have is that the compass in-game on the top of the screen is white. If I remember correctly it can be fixed by some .pak file or a setting in-game.
> 
> It would be great if someone could help me or fix the issues.
> 
> Thank you, Justin
> 
> [launcher.log](https://github.com/user-attachments/files/16639927/launcher.log)

I think the running directory could be wrong

I see this error:
`[FORTNITE_OUTPUT_HANDLER] Detected corrupt build: LogPakFile: Warning: Couldn't find pak signature file '../../../FortniteGame/Content/Paks/pakchunk0-WindowsClient.pak'`
The running directory is:
`[PROCESS] Using working directory: M:\Programme\Old Fortnite\5.4\Fortnite S5.40\Fortnite\.egstore\bps\Install\FortniteGame\Binaries\Win64`
If we join them:
`M:\Programme\Old Fortnite\5.4\Fortnite S5.40\Fortnite\.egstore\bps\Install\FortniteGame\Content\Paks\pakchunk0-WindowsClient.pak`
Does this file actually not exist? If it doesn't is it somewhere else?
@Justin240607

**Comment by Justin240607** [comment]
The File 
`M:\Programme\Old Fortnite\5.4\Fortnite S5.40\Fortnite\.egstore\bps\Install\FortniteGame\Content\Paks\pakchunk0-WindowsClient.pak`
does actually exist but there is no .sig file. Could that be the problem because the logile also states `Couldn't find pak **signature** file `?
![Unbenannt123123](https://github.com/user-attachments/assets/1eefb0ae-556e-495d-933b-f44795398f0f)
![Unbenannt213213](https://github.com/user-attachments/assets/96713ee6-6216-4857-af73-f978168c0f67)

Furthermore wouldn´t the right directory be `M:\Programme\Old Fortnite\5.4\Fortnite S5.40\Fortnite\FortniteGame\Content\Paks`?
There are a lot more .pak files in that directory (attachment).
