### ISSUE TITLE
No Matchmaker Tab 

### ISSUE THREAD

**Issue by VoxyB89** [Auties00/Reboot-Launcher#89]
Can You Please Make it so in the new version we can disable the tab if we want too

**Comment by Auties00** [comment]
There is no matchmaker tab in the latest version though

**Comment by VoxyB89** [comment]
no like in a new new version and can you make it optional? (since i have a local matchmaker tab)

**Comment by Auties00** [comment]
> no like in a new new version and can you make it optional? (since i have a local matchmaker)

If you start your own the launcher won’t start its matchmaker

**Comment by VoxyB89** [comment]
kinda didint understand but okay ig
